### ISSUE TITLE
WARNING This library is still in its early stages of development and thus far from ready for production use.

### ISSUE THREAD

**Issue by kjanoudi** [knicola/tdameritradejs#16]
What exactly is the gap between the current package and one you would consider ready for production use?

**Comment by knicola** [comment]
At this stage, mostly the data streamer. Besides not being complete, it's still in its first implementation and I am not too happy with the overall design so there could be drastic changes. As a matter of fact, breaking changes may be introduced with every minor version to any part of the library until it reaches v1.0.0.

A couple of things to be aware of concerning the data streamer:
* In the case of multiple TDA accounts, it will select the first available. This could affect the account activity stream (ie. order fills).
* The account activity stream is still incomplete and can return XML data rather than JSON.
* Some events could potentially break or at the very least be inconsistent as I haven't picked up all edge cases yet (TDA's api and documentation is a bit rough).

If you can work with that and would like to use this library now, I would definitely suggest using wrapper methods to make it easier to upgrade to newer versions in the future. Also, keep an eye on the changelog file. I try to document all changes as clearly as possible so it'll be easier to know what breaks.

**Comment by kjanoudi** [comment]
@knicola wondering if you have feedback on the authentication piece. Seems like my "refresh token" is expiring a lot sooner than the refresh token expiration date sent back from TDA (90 days or so). After about 30-45 min, i get a 400 error with invalid_grant when i try to refresh the token. It also occurs from curl requests, so i know it's not the library, just wondering if you've had this experience.

![image](https://user-images.githubusercontent.com/4011484/107317102-fe90a480-6a67-11eb-99c7-90a097e27dfb.png)

**Comment by knicola** [comment]
@kjanoudi 

I haven't noticed an issue with the refresh token's expiration time to be honest.

Try running the following once to cache the token info, then run it again after an hour or so
```js
const { TDAmeritrade } = require('@knicola/tdameritrade')
const fs = require('fs')
const opn = require('opn') // npm install opn

const stringify = obj => JSON.stringify(obj, null, 2)

const defaults = {
    apiKey: 'api-key',
    redirectUri: 'https://localhost:8443',
    sslKey: 'selfsigned.key',
    sslCert: 'selfsigned.crt',
}

const config = fs.existsSync('config.json')
    ? Object.assign({}, defaults, require('./config.json'))
    : defaults

const td = new TDAmeritrade(config)

td.on('login', url => opn(url))
td.on('token', () => fs.writeFileSync('config.json', stringify(td.config), 'utf-8'))

td.login().then(async () => {
    td.getAccounts().then(console.log)
})
```
